# Generated by Django 5.1 on 2024-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=15),
        ),
    ]
