# Generated by Django 5.1 on 2024-09-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0002_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('initials', models.CharField(default='', max_length=50)),
                ('color', models.CharField(default='#FF7A00', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='color',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initials',
        ),
    ]
