# Generated by Django 5.1 on 2024-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0003_contact_remove_customuser_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
