# Generated by Django 5.1 on 2024-09-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0003_subtask_task_assigned_to_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
