# Generated by Django 5.1 on 2024-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0005_alter_contact_email_alter_contact_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_users', to='kanbanapp.contact'),
        ),
    ]
