# Generated by Django 5.1 on 2024-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0006_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='initials',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
